---
title: "Proyecto"
author: "Santiago Burgoa, Pablo Deleón, Maximiliano Saldaña"
date: "8 de junio de 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(tidyverse)
library(haven)

datos <- read_dta("Datos/2011_2013panel.dta")

#Datos sobre: info general, cantidad de ocupados segun categorias   
datos_m <- datos %>% select(form, año, cp, a22cargo, a4, a11a1, a11a2, a11a3,b1, starts_with("b2a", ignore.case = FALSE), starts_with("b2b", ignore.case = FALSE), starts_with("b3soc"))

ordenados <- datos%>%
  select(form, año, f21:otrosg3)

problemas <- ordenados %>%
  select(form, año,f21, f22, f23, otrof2a, f2bfaltade)%>%
  rename("primera"=f21, "segunda"=f22, "tercera"=f23, "otro"=otrof2a, "falta de motivación"=f2bfaltade)

ausentismo <- ordenados%>%
  select(f3, f3b1, f3b2, f3b3, otrof3b)%>%
  rename("¿hay ausentismo?"=f3, "primera"=f3b1, "segunda"=f3b2, "tercera"=f3b3, "otro"=otrof3b)

tecno<-ordenados%>%
  select(form, año, g11, g21)%>%
  rename("tecno1"=g11, "tecno2"=g21)
gather(tecno, aspecto, calidad, tecno1, tecno2)

produccion<-ordenados%>%
  select(form, año,g12, g22)%>%
  rename("prod1"=g12, "prod2"=g22)
gather(produccion, aspecto, cantidad, prod1, prod2)

inversion<-ordenados%>%
  select(form, año, g31, g31inv, g31resul, g32, g32inv, g32resul, g33, g33inv, g33resul, g36, g36inv, g36resul, g37, g37inv, g37resul, g38, g38inv, g38resul, g39, g39inv, g39resul)

```



